### ISSUE TITLE
Session load error

### ISSUE THREAD

**Issue by hanpurn** [mdbergmann/Eloquent#58] opened 2020-09-15 13:44 UTC
I am using Eloquent ver.2.6.3 in my macbook.
Recently I didn't do anything, but I got "Session load error".
Please help me how can I exit from this?

<img width="424" alt="Screen Shot 2020-09-15 at 6 13 09 PM" src="https://user-images.githubusercontent.com/15178550/93218152-244aa380-f77f-11ea-84df-7ac8c653de5d.png">

When I click this error message, open new workspace then try to open default Bible...
But it makes waiting icons...

**Comment by hanpurn** [comment] 2020-09-15 13:45
Do I have to uninstall & install this app again?
Or do I have to try to update?

**Comment by mdbergmann** [comment] 2020-09-15 17:33
You could try trashing the file 'DefaultSession.mssess' in '~/Library/Application Support/Eloquent'.

**Comment by hanpurn** [comment] 2020-09-15 18:15
Thank you so much!
I deleted that 'DefaultSession.mssess' file, then no more error message window.
But still I am stuck just after click 'open default Bible'...
Would you help me once more?

Thanks!

<img width="723" alt="Screen Shot 2020-09-15 at 10 41 57 PM" src="https://user-images.githubusercontent.com/15178550/93248245-da74b400-f7a4-11ea-8093-6a3a4cacf7e0.png">

**Comment by mdbergmann** [comment] 2020-09-15 18:32
Hmm. Hard to say. The default bible is "NKRV"?
What happens when you open that bible or another bible through the left side-bar?
What is set as default bible in preferences?

**Comment by hanpurn** [comment] 2020-09-15 18:49
Yes, my default Bible is "NKRV" - New Kor. Rev. Ver.
All the modules what I had is as following.

<img width="185" alt="Screen Shot 2020-09-15 at 11 12 51 PM" src="https://user-images.githubusercontent.com/15178550/93251645-b4054780-f7a9-11ea-85fa-168d87aa82fc.png">

Only Dari module is OK to open, trying any other modules make me stuck...
Ah... one more thing...
In preference, program is suddenly shut down when I choose "Module Font" tab.
I can send you whole message of "Problem Report for Eloquent" in this incident, if it helps.

![Uploading Screen Shot 2020-09-15 at 11.17.02 PM.png…]()

Thanks again...

**Comment by mdbergmann** [comment] 2020-09-15 19:05
OK. It's weird that all of a sudden modules can't load anymore.

You can also try to trash (or move to another place) the preferences file in ~/Library/Preferences.
I believe it's called "org.crosswire.Eloquent.plist."

**Comment by hanpurn** [comment] 2020-09-15 19:35
When I delete "org.crosswire.Eloquent.plist" file, then message tolds I have to download all modules again.
But I have very low internet speed. Nothing response yet.
Is there any other options to try? Thanks!!!

**Comment by mdbergmann** [comment] 2020-09-15 20:06
Save your modules to someplace. They are located in ~/Library/Application Support/Sword.
Then trash preferences.
After a first start with fresh preferences stop Eloquent and put back your modules.

See if that works.

**Comment by hanpurn** [comment] 2020-09-15 20:21
Thank you so much!
I will try tomorrow.
No electric now in here.
My laptop battery out.

**Comment by mdbergmann** [comment] 2020-09-21 05:59
Did it work?

**Comment by mdbergmann** [comment] 2020-11-15 11:22
Closing because unable to reproduce

**Closed by mdbergmann** 2020-11-15 11:22 UTC
Labels: invalid
