### ISSUE TITLE
Apple Silicon

### ISSUE THREAD

**Issue by Berovowilare** [mdbergmann/Eloquent#63] opened 2020-11-28 15:20 UTC
Hello Manfred

If I go to Programme in Systembericht, it says still "Intel" not "Universal". So Eloquent 2.6.4 is not native on Apple Silicon.

**Comment by mdbergmann** [comment] 2020-11-28 16:55
Weird. Because I have built with 'Apple Silicon' architecture.
Need to check.

**Comment by tjdoc** [comment] 2021-06-20 12:34
Confirmed. Eloquent 2.6.6 is not native on Apple Silicon.
Any plans?

**Comment by mdbergmann** [comment] 2021-06-20 12:40
Not for right now. Should work fine with Rosetta2 for the time being.
Eventually there will be an Apple Silicon native version.
Can't be much actually. Maybe I've missed some dependency which breaks the whole chain.

**Comment by Berovowilare** [comment] 2021-06-20 12:45
I saw this last week. Maybe GitHub was not ready? Aber ich komme da nicht wirklich draus;-)

https://www.heise.de/news/GitHub-Desktop-2-9-unterstuetzt-Apple-Silicon-6109506.html

**Comment by mdbergmann** [comment] 2022-08-21 15:20
Fixed with 2.6.7

**Closed** 2022-08-21 15:20 UTC
