### ISSUE TITLE
Crash when syncing install sources

### ISSUE THREAD

**Issue by ccMick** [mdbergmann/Eloquent#61] opened 2020-11-24 11:44 UTC
There's a crash every time you click `Sync Install Sources` in the Module Manager.

Eloquent 2.6.4
macOS 11.0.1 (20B29)

**Comment by mdbergmann** [comment] 2020-11-24 14:09
Indeed.

**Comment by mdbergmann** [comment] 2020-12-17 21:39
I can't reproduce this.
Could append the crash log here?

**Comment by ccMick** [comment] 2020-12-18 16:54
So when I click it now, I get the beachball for a very long time, but eventually the app starts responding again. I can't remember now if it was actually crashing before, or whether it beachballed for so long that I lost patience and force quit it. Sorry if that was a false alarm. Perhaps there's also a way to stop the hang.

**Comment by mdbergmann** [comment] 2020-12-18 16:59
The thing here is that this is not an asynchronous process.
The server is 'asked' synchronously and if that takes longer until we get the response than macOS shows the beachball.
That's nothing bad in itself.
The alternative is that I can make this an asynchronous process, lock the screen and show a spinning wheel instead.

**Comment by mdbergmann** [comment] 2020-12-18 17:14
Are you OK if I close this?

**Comment by ccMick** [comment] 2020-12-18 22:10
Ah gotcha, thanks. Yup, close it.

**Closed** 2020-12-25 11:58 UTC
Labels: Feedback required, bug
